# -*- coding: utf-8 -*-
"""parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JPhxPWPC0PjWpaKjCbw86Ikr8F-BavWe
"""

# @title 1. Cài đặt thư viện xử lý ngôn ngữ
!pip install pyvi

import json
import os
import re
import hashlib
import unicodedata
from pyvi import ViTokenizer
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')
print("✅ Đã cài đặt môi trường và kết nối Drive!")

# @title 2. Cấu hình File Input/Output
# --- SỬA ĐƯỜNG DẪN TẠI ĐÂY ---
INPUT_FILE = '/content/drive/MyDrive/otofun_all_docs.jsonl'  # Đường dẫn file gốc của bạn
OUTPUT_FILE = '/content/drive/MyDrive/SEG301_Project/data_clean/otofun_cleanv2.jsonl' # Đường dẫn file sau khi làm sạch

# Tạo thư mục output nếu chưa có
os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

print(f"📂 Input: {INPUT_FILE}")
print(f"📂 Output: {OUTPUT_FILE}")

# @title 3. Định nghĩa hàm Cleaning & Tokenization

def clean_and_tokenize(text):
    if not text:
        return ""

    # 1. Chuẩn hóa Unicode (Fix lỗi font, tổ hợp/dựng sẵn)
    text = unicodedata.normalize('NFC', text)

    # 2. Loại bỏ thẻ HTML và Script rác
    # Xóa script/style
    text = re.sub(r'<(script|style).*?>.*?</\1>', '', text, flags=re.DOTALL)
    # Xóa thẻ HTML còn lại (VD: <b>, <br>, <div>)
    text = re.sub(r'<.*?>', ' ', text)

    # 3. Xử lý rác (Giữ lại Tiếng Việt, Tiếng Anh, số và dấu câu cơ bản)
    # Loại bỏ URL
    text = re.sub(r'http\S+', '', text)
    # Loại bỏ Email
    text = re.sub(r'\S+@\S+', '', text)
    # (Tùy chọn) Chuyển về chữ thường để Index hiệu quả hơn
    text = text.lower()

    # Loại bỏ khoảng trắng thừa
    text = re.sub(r'\s+', ' ', text).strip()

    # 4. Tách từ tiếng Việt (Word Segmentation) bằng PyVi
    # Output: "sinh viên đại học fpt" -> "sinh_viên đại_học fpt"
    tokenized_text = ViTokenizer.tokenize(text)

    return tokenized_text

# Test thử
sample = "Học lập   trình <b>Python</b> tại    FPT University! &lt;script&gt;alert(1)&lt;/script&gt;"
print(f"Gốc: {sample}")
print(f"Sạch: {clean_and_tokenize(sample)}")

# @title 3. Định nghĩa hàm Cleaning & Tokenization (Đã update Filter & English Fix)

def clean_and_tokenize(text):
    if not text:
        return None

    # 1. Chuẩn hóa Unicode (Fix lỗi font, tổ hợp/dựng sẵn)
    text = unicodedata.normalize('NFC', text)

    # 2. Loại bỏ thẻ HTML và Script rác
    # Thay thế bằng khoảng trắng ' ' để tránh dính từ (VD: <div>A</div><div>B</div> -> A B)
    text = re.sub(r'<(script|style).*?>.*?</\1>', ' ', text, flags=re.DOTALL)
    text = re.sub(r'<.*?>', ' ', text)

    # 3. Xử lý rác & Tách biệt Tiếng Anh (QUAN TRỌNG)
    # Loại bỏ URL & Email
    text = re.sub(r'http\S+', ' ', text)
    text = re.sub(r'\S+@\S+', ' ', text)

    # --- LOGIC MỚI: Tách từ Tiếng Anh khỏi dấu câu ---
    # Thay thế TẤT CẢ ký tự KHÔNG PHẢI là: Chữ (Việt+Anh), Số, Khoảng trắng -> bằng khoảng trắng.
    # Điều này giúp "Python," -> "python" (tách dấu phẩy ra)
    text = re.sub(r'[^\w\sàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ]', ' ', text)

    # Chuyển về chữ thường
    text = text.lower()

    # Loại bỏ khoảng trắng thừa (Do bước thay thế trên tạo ra nhiều khoảng trắng)
    text = re.sub(r'\s+', ' ', text).strip()

    if not text:
        return None

    # 4. Tách từ tiếng Việt (Word Segmentation) bằng PyVi
    # Output: "sinh viên đại học fpt" -> "sinh_viên đại_học fpt"
    # Các từ tiếng Anh như "python", "java" sẽ được giữ nguyên, không bị tách bậy
    tokenized_text = ViTokenizer.tokenize(text)

    # 5. --- LOGIC MỚI: Kiểm tra độ dài (Min Word Count) ---
    # Đếm số lượng token (từ)
    word_count = len(tokenized_text.split())

    # Nếu dưới 50 từ -> Trả về None (Để code bên ngoài biết và loại bỏ)
    if word_count < 50:
        return None

    return tokenized_text

# --- Test thử Logic mới ---
# Ví dụ 1: Comment ngắn (sẽ bị loại)
short_sample = "Bài viết này hay quá, cảm ơn chủ thớt."
print(f"Test ngắn (Gốc): {short_sample}")
print(f"Kết quả: {clean_and_tokenize(short_sample)}") # Mong đợi: None

print("-" * 20)

# Ví dụ 2: Comment dài + Tiếng Anh dính dấu câu (sẽ được giữ và tách đúng)
long_sample = """
Mình thấy khóa học này về Python,Java và C++ rất ổn áp.
Giảng viên dạy nhiệt tình, support tận răng.
Tuy nhiên phần machine learning thì hơi khó hiểu một chút, cần có kiến thức toán đại cương.
Nhưng tóm lại là đáng tiền, mọi người nên thử nhé.
Cộng đồng voz cũng review tốt về khóa này lắm.
À quên, nhớ cài đặt môi trường Anaconda trước khi học nhé, không là lỗi tùm lum đó.
Chúc các bác học tốt và sớm kiếm được việc làm ngon nghẻ nha.
"""
# (Lưu ý: Đoạn text trên khoảng > 50 từ để test pass)
processed = clean_and_tokenize(long_sample)

if processed:
    print(f"Test dài (Đã tách từ): {processed[:100]}...") # In thử 100 ký tự đầu
    print(f"Số từ đếm được: {len(processed.split())}")
else:
    print("Test dài bị loại (Chưa đủ 50 từ).")

# @title 4. Chạy Pipeline: Đọc -> De-duplicate -> Clean -> Ghi

def process_data_pipeline(input_path, output_path):
    if not os.path.exists(input_path):
        print("❌ Lỗi: Không tìm thấy file Input!")
        return

    print("🚀 Bắt đầu xử lý dữ liệu...")

    # Tập hợp chứa mã hash của nội dung để kiểm tra trùng lặp
    seen_hashes = set()

    count_in = 0
    count_out = 0
    count_dup = 0

    with open(input_path, 'r', encoding='utf-8') as f_in, \
         open(output_path, 'w', encoding='utf-8') as f_out:

        for line in f_in:
            count_in += 1
            if count_in % 10000 == 0:
                print(f"...Đang xử lý dòng thứ {count_in}")

            try:
                # 1. Parse JSON
                doc = json.loads(line)

                # Lấy trường nội dung chính (text hoặc content)
                raw_text = doc.get('text') or doc.get('content', '')

                # Bỏ qua nếu nội dung quá ngắn
                if len(raw_text) < 10:
                    continue

                # 2. De-duplication (Loại bỏ trùng lặp)
                # Tạo mã hash MD5 của văn bản gốc
                text_hash = hashlib.md5(raw_text.encode('utf-8')).hexdigest()

                if text_hash in seen_hashes:
                    count_dup += 1
                    continue # Bỏ qua dòng này vì đã gặp rồi

                seen_hashes.add(text_hash)

                # 3. Clean & Tokenize
                clean_text = clean_and_tokenize(raw_text)
                if clean_text is None:
                     continue

                # Nếu có dữ liệu thì lưu...
                doc['text_clean'] = clean_text
                # Bỏ qua nếu sau khi clean không còn gì (toàn ký tự đặc biệt)
                if len(clean_text) < 5:
                    continue

                # 4. Cập nhật lại doc và ghi xuống file
                doc['text_clean'] = clean_text # Lưu vào trường mới hoặc đè lên trường cũ

                # Có thể xóa trường raw để giảm dung lượng file
                # del doc['text']

                f_out.write(json.dumps(doc, ensure_ascii=False) + '\n')
                count_out += 1

            except Exception as e:
                # Bỏ qua các dòng lỗi JSON format
                continue

    print("-" * 30)
    print(f"✅ HOÀN TẤT!")
    print(f"📊 Tổng số dòng input: {count_in}")
    print(f"🗑️ Số dòng trùng lặp (Deleted): {count_dup}")
    print(f"💾 Số dòng sạch được lưu: {count_out}")
    print(f"📂 File kết quả: {output_path}")

# Chạy hàm
process_data_pipeline(INPUT_FILE, OUTPUT_FILE)

# @title 5. Kiểm tra mẫu dữ liệu sạch
print("--- 5 Dòng dữ liệu sau khi xử lý ---")
try:
    with open(OUTPUT_FILE, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i >= 5: break
            data = json.loads(line)
            # In ra trường text_clean
            print(f"[{i+1}] {data.get('text_clean', '')[:200]}...")
except:
    print("Chưa có file output.")

# @title 6. Ép buộc đồng bộ dữ liệu (Force Sync)
import os

# Đường dẫn file output của bạn
FILE_TO_SYNC = OUTPUT_FILE

print("⏳ Đang ép buộc đồng bộ dữ liệu xuống ổ cứng...")

# 1. Đảm bảo file được flush từ Python buffer xuống OS buffer
with open(FILE_TO_SYNC, 'a') as f:
    f.flush()
    os.fsync(f.fileno())

# 2. Kiểm tra lại số dòng thực tế ĐANG CÓ trên Colab (trước khi tải về)
count_check = 0
with open(FILE_TO_SYNC, 'r', encoding='utf-8') as f:
    for _ in f:
        count_check += 1

print(f"✅ Số dòng thực tế đang nằm trên Colab: {count_check}")

if count_check == 1109949:
    print("🎉 Dữ liệu đã đầy đủ! Bạn có thể tải về an toàn.")
    print("Mẹo: Hãy đợi khoảng 1-2 phút sau khi thấy thông báo này rồi hãy vào Drive tải.")
else:
    print(f"⚠️ Vẫn còn lệch {1109949 - count_check} dòng. Hãy chạy lại cell này hoặc đợi thêm vài phút.")